# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CC_IMG' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CC_IMG
  pod 'CocoaLumberjack/Swift'
  pod "PromiseKit", "~> 6.0"
  pod 'Alamofire'
  pod 'PromiseKit/Alamofire', '~> 6.0'
  pod 'SDWebImage'
end
